MVC/MVC/Controllers/employeeController.cs
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class employeeController : Controller
    {
        // GET: employee
        UHGDBEntities context;
        public employeeController()
        {
            context = new UHGDBEntities();
        }
        public ActionResult ShowAll()
        {
            var result = context.emps.ToList();
            return View(result);
        }
        [HttpGet]
        public ActionResult AddNew()
        {
            emp em = new emp();
            return View(em);
        }
        [HttpPost]
        public ActionResult AddNew(emp em)
        {
            context.emps.Add(em);
            context.SaveChanges();
            return RedirectToAction("ShowAll");
        }

    }

}

MVC/MVC/Views/employee/AddNew.cshtml
@using MVC.Models;
@model emp
@{
    ViewBag.Title = "AddNew";
}

<h2>AddNew</h2>
@using (Html.BeginForm("AddNew", "employee", FormMethod.Post))
{
    <label for="code">Code</label>
    <br />
    @Html.TextBoxFor(c=>c.code)
    <br />
    <label for="name" >Name</label>
    <br />
    @Html.TextBoxFor(c=>c.name)
    <br />
    <label for="salary">Salary</label>
    <br />
    @Html.TextBoxFor(c => c.salary)
    <br />
    <label for="deptid">Deptid</label>
    <br />
    
    <input type="text" id="deptid" name="deptid" />
    <br />
    <input type="submit" value="Submit" />
}

MVC/MVC/Views/employee/ShowAll.cshtml
@using MVC.Models;
@model List<emp>
@{
    ViewBag.Title = "ShowAll";
}

<h2>ShowAll</h2>
<table class="table table-hover">
        @foreach(emp em in Model)
        {
    <tr>
        <td>@em.code</td>
        <td>@em.name</td>
        <td>@em.salary</td>
        <td>@em.deptid</td>
        </tr>

        }
    
</table>